name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - master
      - feat/*
  paths:
    exclude:
      - 'testem1/*'
      - 'testem2/*'

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - script: |
      echo "Hello from '/' root folder."