apiVersion: apps/v1
kind: Deployment
metadata:
  name: testem1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testem1
  template:
    metadata:
      labels:
        app: testem1
    spec:
      containers:
      - name: testem1
        image: fernandobaia/servicea:v1
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: testem1-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 3333
  selector:
    app: testem1