# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'testem2/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from 'testem2'"